name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker image
      uses: docker://beevelop/nodejs-python
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - run: npm install
    - run: npm test
    services:
      mongodb:
       image: mongo
       ports:
        - 27017:27017
    env:
      CI: true
      SERVER_PORT: 3001
      DB_URL: "mongodb://localhost:27017/meatapi"
