name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-16.04

    steps:
    - uses: actions/checkout@v2
    - name: Docker image
      uses: docker://beevelop/nodejs-python
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - run: npm install
    - run: npm test
    services:
      mongodb:
       image: mongo
       ports:
        - 27017:27017
    env:
      CI: true
      SERVER_PORT: 3001
      DB_URL: "mongodb://localhost/meatapi"

  deploy:

    runs-on: ubuntu-16.04

    needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Docker image
      uses: docker://beevelop/nodejs-python
    - name: Before deploy
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
      run: |
        mkdir -p ~/.ssh
        echo "$DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        eval "$(ssh-agent -s)"
        ssh-add ~/.ssh/id_rsa
        ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts
    - name: Deploy new version
      env:
        DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
      run: |
        ssh deploy@$DEPLOY_SERVER "source ~/.nvm/nvm.sh; cd meat-api; git pull; npm i; npm run build; cd; pm2 startOrReload ecosystem.config.js"