# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

on:
  pull_request:
    branches: [ master ]

jobs:
  test:

    runs-on: ubuntu-16.04

    strategy:
      matrix:
        node-version: [12]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: |
          ~/cache
          !~/cache/exclude
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Create mongoDB Docker container for API testing
      uses: DigiPie/mongo-action@v1.0.0
    - run: npm install
    - run: npm test
      env:
        CI: true
        SERVER_PORT: 3001
        DB_URL: "mongodb://localhost/meatapi"
